# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'
#source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'NveEffectKitDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  
  # Pods for MeicamLive
  pod 'NvEffectModule',         :path => '../NvEffectModule'

end

 #清理版本警告
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
    end
  end
end
